import { element } from '../primitives/element.function';
import { selfClosingElement } from '../primitives/self-closing-element.function';

import { TAttributes } from '../types/attributes.type';

import { CSSProperties } from './lib/types/css-properties.type';
import { TElementProps } from './lib/types/element-props.type';

import { styleManager } from './lib/constants/style-manager.constant';
import { asId } from './lib/functions/as-id.function';
import { asElementFactory } from './lib/functions/as-element-factory.function';
import { extractStyle } from './lib/functions/extract-style.function';
import { setAttrs } from './lib/functions/set-element-attributes.function';
import { setElementStyle } from './lib/functions/set-element-style.function';
import { setElementStyles } from './lib/functions/set-element-styles.function';
import { styleOn } from './lib/functions/style-on.function';
import { styleOnFocus } from './lib/functions/style-on-focus.function';
import { styleOnPointerEnter } from './lib/functions/style-on-pointer-enter.function';
import { styled } from './lib/functions/styled.function';

export { CSSProperties };
export { TElementProps };
export { styleManager };
export { asId };
export { asElementFactory };
export { extractStyle };
export { setAttrs };
export { setElementStyle };
export { setElementStyles };
export { styleOn };
export { styleOnFocus };
export { styleOnPointerEnter };
export { styled };

// Element factories
export const $a = asElementFactory(element.bind(null, 'a'));
export const $abbr = asElementFactory(element.bind(null, 'abbr'));
export const $address = asElementFactory(element.bind(null, 'address'));
export const $area = asElementFactory((_, attrs) => selfClosingElement('area', attrs));
export const $article = asElementFactory(element.bind(null, 'article'));
export const $aside = asElementFactory(element.bind(null, 'aside'));
export const $audio = asElementFactory(element.bind(null, 'audio'));
export const $b = asElementFactory(element.bind(null, 'b'));
export const $base = asElementFactory((_, attrs) => selfClosingElement('base', attrs));
export const $bdi = asElementFactory(element.bind(null, 'bdi'));
export const $bdo = asElementFactory(element.bind(null, 'bdo'));
export const $blockquote = asElementFactory(element.bind(null, 'blockquote'));
export const $body = asElementFactory(element.bind(null, 'body'));
export const $br = asElementFactory((_, attrs) => selfClosingElement('br', attrs));
export const $button = asElementFactory(element.bind(null, 'button'));
export const $canvas = asElementFactory(element.bind(null, 'canvas'));
export const $caption = asElementFactory(element.bind(null, 'caption'));
export const $cite = asElementFactory(element.bind(null, 'cite'));
export const $code = asElementFactory(element.bind(null, 'code'));
export const $col = asElementFactory((_, attrs) => selfClosingElement('col', attrs));
export const $colgroup = asElementFactory(element.bind(null, 'colgroup'));
export const $data = asElementFactory(element.bind(null, 'data'));
export const $datalist = asElementFactory(element.bind(null, 'datalist'));
export const $dd = asElementFactory(element.bind(null, 'dd'));
export const $del = asElementFactory(element.bind(null, 'del'));
export const $details = asElementFactory(element.bind(null, 'details'));
export const $dfn = asElementFactory(element.bind(null, 'dfn'));
export const $dialog = asElementFactory(element.bind(null, 'dialog'));
export const $div = asElementFactory(element.bind(null, 'div'));
export const $dl = asElementFactory(element.bind(null, 'dl'));
export const $dt = asElementFactory(element.bind(null, 'dt'));
export const $em = asElementFactory(element.bind(null, 'em'));
export const $embed = asElementFactory((_, attrs) => selfClosingElement('embed', attrs));
export const $fieldset = asElementFactory(element.bind(null, 'fieldset'));
export const $figcaption = asElementFactory(element.bind(null, 'figcaption'));
export const $figure = asElementFactory(element.bind(null, 'figure'));
export const $footer = asElementFactory(element.bind(null, 'footer'));
export const $form = asElementFactory(element.bind(null, 'form'));
export const $h1 = asElementFactory(element.bind(null, 'h1'));
export const $h2 = asElementFactory(element.bind(null, 'h2'));
export const $h3 = asElementFactory(element.bind(null, 'h3'));
export const $h4 = asElementFactory(element.bind(null, 'h4'));
export const $h5 = asElementFactory(element.bind(null, 'h5'));
export const $h6 = asElementFactory(element.bind(null, 'h6'));
export const $head = asElementFactory(element.bind(null, 'head'));
export const $header = asElementFactory(element.bind(null, 'header'));
export const $hgroup = asElementFactory(element.bind(null, 'hgroup'));
export const $hr = asElementFactory((_, attrs) => selfClosingElement('hr', attrs));
export const $html = asElementFactory(element.bind(null, 'html'));
export const $i = asElementFactory(element.bind(null, 'i'));
export const $iframe = asElementFactory(element.bind(null, 'iframe'));
export const $img = asElementFactory((_, attrs) => selfClosingElement('img', attrs));
export const $input = asElementFactory((_, attrs) => selfClosingElement('input', attrs));
export const $ins = asElementFactory(element.bind(null, 'ins'));
export const $kbd = asElementFactory(element.bind(null, 'kbd'));
export const $label = asElementFactory(element.bind(null, 'label'));
export const $legend = asElementFactory(element.bind(null, 'legend'));
export const $li = asElementFactory(element.bind(null, 'li'));
export const $link = asElementFactory((_, attrs) => selfClosingElement('link', attrs));
export const $main = asElementFactory(element.bind(null, 'main'));
export const $map = asElementFactory(element.bind(null, 'map'));
export const $mark = asElementFactory(element.bind(null, 'mark'));
export const $math = asElementFactory(element.bind(null, 'math'));
export const $menu = asElementFactory(element.bind(null, 'menu'));
export const $meta = asElementFactory((_, attrs) => selfClosingElement('meta', attrs));
export const $meter = asElementFactory(element.bind(null, 'meter'));
export const $nav = asElementFactory(element.bind(null, 'nav'));
export const $noscript = asElementFactory(element.bind(null, 'noscript'));
export const $object = asElementFactory(element.bind(null, 'object'));
export const $ol = asElementFactory(element.bind(null, 'ol'));
export const $optgroup = asElementFactory(element.bind(null, 'optgroup'));
export const $option = asElementFactory(element.bind(null, 'option'));
export const $output = asElementFactory(element.bind(null, 'output'));
export const $p = asElementFactory(element.bind(null, 'p'));
export const $picture = asElementFactory(element.bind(null, 'picture'));
export const $pre = asElementFactory(element.bind(null, 'pre'));
export const $progress = asElementFactory(element.bind(null, 'progress'));
export const $q = asElementFactory(element.bind(null, 'q'));
export const $rp = asElementFactory(element.bind(null, 'rp'));
export const $rt = asElementFactory(element.bind(null, 'rt'));
export const $ruby = asElementFactory(element.bind(null, 'ruby'));
export const $s = asElementFactory(element.bind(null, 's'));
export const $samp = asElementFactory(element.bind(null, 'samp'));
export const $script = asElementFactory(element.bind(null, 'script'));
export const $section = asElementFactory(element.bind(null, 'section'));
export const $select = asElementFactory(element.bind(null, 'select'));
export const $slot = asElementFactory(element.bind(null, 'slot'));
export const $small = asElementFactory(element.bind(null, 'small'));
export const $source = asElementFactory((_, attrs) => selfClosingElement('source', attrs));
export const $span = asElementFactory(element.bind(null, 'span'));
export const $strong = asElementFactory(element.bind(null, 'strong'));
export const $style = asElementFactory(element.bind(null, 'style'));
export const $sub = asElementFactory(element.bind(null, 'sub'));
export const $summary = asElementFactory(element.bind(null, 'summary'));
export const $sup = asElementFactory(element.bind(null, 'sup'));
export const $table = asElementFactory(element.bind(null, 'table'));
export const $tbody = asElementFactory(element.bind(null, 'tbody'));
export const $td = asElementFactory(element.bind(null, 'td'));
export const $template = asElementFactory(element.bind(null, 'template'));
export const $textarea = asElementFactory(element.bind(null, 'textarea'));
export const $tfoot = asElementFactory(element.bind(null, 'tfoot'));
export const $th = asElementFactory(element.bind(null, 'th'));
export const $thead = asElementFactory(element.bind(null, 'thead'));
export const $time = asElementFactory(element.bind(null, 'time'));
export const $title = asElementFactory(element.bind(null, 'title'));
export const $tr = asElementFactory(element.bind(null, 'tr'));
export const $track = asElementFactory((_, attrs) => selfClosingElement('track', attrs));
export const $u = asElementFactory(element.bind(null, 'u'));
export const $ul = asElementFactory(element.bind(null, 'ul'));
export const $var = asElementFactory(element.bind(null, 'var'));
export const $video = asElementFactory(element.bind(null, 'video'));
export const $wbr = asElementFactory((_, attrs) => selfClosingElement('wbr', attrs));