import {
  dashesLettersNumbers,
  dashesLettersNumbersSpaces,
  zip,
  phone,
  phonePlusOne,
  code,
  url,
  protocol,
  firstSpaceLast,
  passwordNumber,
  passwordUpper,
  passwordLower,
  passwordSpecial,
  ssn,
  numeric,
  duns,
  lastFourSocial,
  ein,
  stateShort,
  email, domain,
  emailDomain,
} from '@onivoro/isomorphic/common';

// TODO: ELIMINATE THIS CONSTANT
// IT'S ONLY HERE FOR NOW BECAUSE THERE'S ZERO TIME TO REWRITE EXISTING IMPORTS
export const formatRegexes = {
  dashesLettersNumbers,
  dashesLettersNumbersSpaces,
  zip,
  phone,
  phonePlusOne,
  code,
  url,
  protocol,
  firstSpaceLast,
  passwordNumber,
  passwordUpper,
  passwordLower,
  passwordSpecial,
  ssn,
  numeric,
  duns,
  lastFourSocial,
  ein,
  stateShort,
  email,
  domain,
  emailDomain,
};
