export const MCP_AUDIT_EMAIL_RESOLVER = Symbol('MCP_AUDIT_EMAIL_RESOLVER');
export const MCP_AUDIT_EVENT_RESOLVER = Symbol('MCP_AUDIT_EVENT_RESOLVER');
export const MCP_AUDIT_SINK = Symbol('MCP_AUDIT_SINK');
