export const AGENTIC_CHAT_CONFIG = 'AGENTIC_CHAT_CONFIG';
export const AGENTIC_EVENT_PUBLISHER = 'AGENTIC_EVENT_PUBLISHER';
export const AGENTIC_ID_GENERATOR = 'AGENTIC_ID_GENERATOR';
export const AGENTIC_MODEL_PROVIDER = 'AGENTIC_MODEL_PROVIDER';
export const AGENTIC_REPOSITORIES = 'AGENTIC_REPOSITORIES';
export const AGENTIC_TOOL_PROVIDER = 'AGENTIC_TOOL_PROVIDER';
